services:
  frontend:
    build: ./frontend
    init: true
    environment:
      VITE_API_URL: "http://backend:3000"
    ports:
      - "80:80"


  backend:
    build: ./backend
    init: true
    ports:
      - "3000:3000"